id: AE7555410
title: The Dhāraṇī of Amitāyus
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:43:46.163372
  last_modified_at: 2022-03-01 02:43:46.163375
