id: AE7555410
title: 'The Bestowal of Supreme Immortality: A Prayer to the Lineage of Mitrayogin’s
  White and Red Amitāyus'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:43:46.161865
  last_modified_at: 2022-03-01 02:43:46.161868
