id: AE7555410
title: A Prayer to Amitāyus
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:43:46.157060
  last_modified_at: 2022-03-01 02:43:46.157064
