id: AE7555410
title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily Practice
  Uniting the Short Lineages of Amitāyus and Hayagrīva'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:43:46.169072
  last_modified_at: 2022-03-01 02:43:46.169075
