id: AE7555410
title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret Pith
  Instructions on Attaining Vajra Longevity'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:43:46.164628
  last_modified_at: 2022-03-01 02:43:46.164631
