id: AE7555410
title: How to Recite the Dhāraṇīsūtra of Amitāyus
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:43:46.160295
  last_modified_at: 2022-03-01 02:43:46.160297
