id: AE7555410
title: The Sūtra of Boundless Life and Wisdom
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:43:46.167405
  last_modified_at: 2022-03-01 02:43:46.167407
